server:
  port: 8082
  servlet:
    context-path: /tc
spring:
  application:
    name: tc
  cloud:
    nacos:
      discovery:
        server-addr: slave2:8848 #Nacos服务注册中心地址
      config:
        server-addr: slave2:8848
        enabled: false
    #sentinel:
      #transport:
        #dashboard: localhost:9999 #配置Sentinel dashboard地址
        #port: 8719
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/converter?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #  mapper文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  #  实体类
  type-aliases-package: com.zx.hoperun.tc.entity
logging:
  config: classpath:log4j2.xml
management:
  endpoint:
    sentinel:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持