package com.zx.hoperun.tc.entity;

import lombok.Data;

@Data
public class TcData {
    private String xyp_t01aazhzz ;
    private String xyp_t01abdzbz ;
    private String xyp_t01aahzbz ;
    private String xyp_t01ackzbz;
    private String xyp_t01cczgbc ;
    private String xyp_t01adjzzz;
    private String xyp_t01adzfbz ;
    private String xyp_model_score_mid;
    private String xyp_t01acizza ;
    private String xyp_t01adjzzc;
    private String xyp_t01aakzzz;
    private String xyp_t02cchzza_cchzzz ;
    private String xyp_t01acfzbc ;
    private String xyp_t02cchzzc_cchzzz ;
    private String xyp_t01degzbc ;
    private String xyp_t01abgzzc ;
    private String xyp_t01dejzzc;
    private String xyp_t02cckzbc_cckzbz;
    private String xyp_t01cclzba ;
    private String xyp_t01ackzaz ;
    private String xyp_t01cclzbc;
    private String xyp_t01aazgzc ;
    private String xyp_t01aafzzc ;
    private String xyp_t01adgzbc ;
    private String xyp_t01abjzbc;
    private String xyp_t03td148;
    private String xyp_t01adgzba ;
    private String xyp_t01delzbc;
    private String xyp_t02acizba_aczzba ;
    private String xyp_t01abzfzz ;
    private String xyp_t01aafzzz ;
    private String xyp_t01aczhbc ;
    private String xyp_t01acczzz ;
    private String xyp_t01aczgbz ;
    private String xyp_t03td053;
    private String xyp_t01ccgzbc ;
    private String xyp_t02achzza_achzzz ;
    private String xyp_var9 ;
    private String xyp_var8 ;
    private String xyp_t01adhzbc ;
    private String xyp_var7 ;
    private String xyp_t02ackzbc_ackzbz;
    private String xyp_t01aalzzc;
    private String xyp_t01defzbz ;
    private String xyp_t02ccgzzc_ccgzzz ;
    private String xyp_t01acdzzz ;
    private String xyp_t01aaizba ;
    private String xyp_t02acfzza_acfzzz ;
    private String xyp_t01aclzbc;
    private String xyp_t02achzbc_achzbz ;
    private String xyp_t01aaizbz;
    private String xyp_t02ccizbc_cczzbc;
    private String xyp_t02acizbc_acizbz;
    private String xyp_t01aazfzc ;
    private String xyp_t03td045;
    private String xyp_t01abezbz ;
    private String xyp_t02acjzbc_acjzbz;
    private String xyp_t01acizzz;
    private String xyp_var6 ;
    private String xyp_t01cczfbz ;
    private String xyp_var5 ;
    private String xyp_var4 ;
    private String xyp_var3 ;
    private String xyp_var2 ;
    private String xyp_var1 ;
    private String xyp_t01acfzbz ;
    private String xyp_t02cczzza_cczzzz ;
    private String xyp_t02ccfzbc_cczzbc ;
    private String xyp_t01aczgbc ;
    private String xyp_t01bbzzza ;
    private String xyp_t01cczzzz;
    private String xyp_t01aalzzz;
    private String xyp_t01aazfzz ;
    private String xyp_t01adzgzc ;
    private String xyp_t01aczfbz ;
    private String xyp_t01adczbz ;
    private String xyp_cpl0058 ;
    private String xyp_t01aczzzz;
    private String xyp_t01adfzzz ;
    private String xyp_cpl0059 ;
    private String xyp_t01cczezz ;
    private String xyp_t01aagzzc ;
    private String xyp_t03td111;
    private String xyp_cpl0056 ;
    private String xyp_t02acfzbc_aczzbc ;
    private String xyp_t01bazzba ;
    private String xyp_cpl0057 ;
    private String xyp_t02cchzba_cchzbz ;
    private String xyp_t01abkzbc;
    private String xyp_t01bazzbc;
    private String xyp_t03td115;
    private String xyp_t01abkzba ;
    private String xyp_cpl0050;
    private String xyp_cpl0051;
    private String xyp_t01adfzzc ;
    private String xyp_cpl0054 ;
    private String xyp_t01bazzbz;
    private String xyp_cpl0055 ;
    private String xyp_cpl0052 ;
    private String xyp_t01dekzzz;
    private String xyp_t01adfzza ;
    private String xyp_cpl0053 ;
    private String xyp_t01aadzbz ;
    private String fee_status;
    private String xyp_t01acjzzz;
    private String xyp_t02cclzba_cclzbz ;
    private String xyp_t01abfzba ;
    private String xyp_t01aclzbz;
    private String xyp_cpl0069 ;
    private String xyp_cpl0067 ;
    private String xyp_cpl0068;
    private String xyp_cpl0061 ;
    private String xyp_cpl0062 ;
    private String xyp_t01cchzzc ;
    private String xyp_cpl0060 ;
    private String xyp_model_score_high;
    private String xyp_cpl0065;
    private String xyp_cpl0066;
    private String xyp_cpl0063 ;
    private String xyp_t01abkzbz;
    private String xyp_t01adkzzc;
    private String xyp_cpl0064 ;
    private String xyp_t01aajzba ;
    private String xyp_t01aczfbc ;
    private String xyp_t01acgzbc ;
    private String xyp_t01aczfba ;
    private String xyp_t01dekzzc;
    private String xyp_t01aczzzc;
    private String xyp_t01adzfzc ;
    private String xyp_t01adizbz;
    private String xyp_cpl0078;
    private String xyp_t01abfzbz ;
    private String xyp_t02dezgzz_dezzzz ;
    private String xyp_t02achzzc_achzzz ;
    private String xyp_cpl0079 ;
    private String xyp_t01ccczza ;
    private String xyp_t01cczhbc ;
    private String xyp_cpl0072;
    private String xyp_t01aaezbc ;
    private String xyp_cpl0073;
    private String xyp_t01aczhzc ;
    private String xyp_cpl0070 ;
    private String xyp_cpl0071;
    private String xyp_cpl0076;
    private String xyp_t01ackzza ;
    private String xyp_cpl0077;
    private String xyp_t01achzaz ;
    private String xyp_t01aahzza ;
    private String xyp_t01ackzzc;
    private String xyp_cpl0074;
    private String xyp_t02acezza_aczzza ;
    private String xyp_cpl0075;
    private String xyp_t01abizzc;
    private String xyp_t01achzbc ;
    private String xyp_t01cckzaz ;
    private String xyp_t01adlzzc;
    private String xyp_t02cczzba_cczzbz ;
    private String xyp_t01ccfzbc ;
    private String xyp_t01ccizza ;
    private String xyp_t02ccfzzc_cczzzc ;
    private String xyp_t01adizbc;
    private String xyp_t01ablzbc;
    private String xyp_t01ccizzc;
    private String xyp_cpl0083 ;
    private String xyp_cpl0081;
    private String xyp_cpl0082 ;
    private String xyp_t02acjzzc_acjzzz;
    private String xyp_t02ackzzc_ackzzz;
    private String xyp_t01acezzz ;
    private String xyp_cpl0080 ;
    private String xyp_t02aclzzc_aclzzz;
    private String xyp_t01degzzc ;
    private String xyp_t01adjzba ;
    private String xyp_t02ccfzba_ccfzbz ;
    private String xyp_t02ccezzc_cczzzc ;
    private String xyp_t01abgzbc ;
    private String xyp_t01acfzza ;
    private String xyp_t01abjzzc;
    private String xyp_t02ccfzbc_ccfzbz ;
    private String xyp_t02ccezza_cczzza ;
    private String xyp_cpl0014;
    private String xyp_cpl0015;
    private String xyp_cpl0012 ;
    private String xyp_t01cczgzz ;
    private String xyp_t01abzfbz ;
    private String xyp_t01bbzzbz;
    private String xyp_cpl0013 ;
    private String xyp_cpl0018;
    private String xyp_t02acezba_acezbz ;
    private String xyp_cpl0019 ;
    private String xyp_cpl0016;
    private String xyp_t01adjzbc;
    private String xyp_cpl0017 ;
    private String xyp_t01cclzzc;
    private String xyp_t01bbzzbc;
    private String xyp_t01bbzzba ;
    private String xyp_t01aczgzc ;
    private String xyp_cpl0010 ;
    private String xyp_t01aczgza ;
    private String xyp_cpl0011 ;
    private String xyp_t01adzzba ;
    private String xyp_t01aazhaz ;
    private String xyp_t01aakzba ;
    private String xyp_t01cczfza ;
    private String xyp_t01addzbz ;
    private String xyp_t01cczfzc ;
    private String xyp_model_score_low ;
    private String xyp_cpl0025 ;
    private String xyp_cpl0026;
    private String xyp_cpl0023 ;
    private String xyp_cpl0024;
    private String xyp_t01abzzza ;
    private String xyp_cpl0029;
    private String xyp_t02acczza_acczzz ;
    private String xyp_cpl0027 ;
    private String xyp_cpl0028;
    private String xyp_t01ccgzza ;
    private String xyp_t01aafzbc ;
    private String xyp_t01abzfba ;
    private String xyp_t01adgzzc ;
    private String xyp_t01aaizzc;
    private String xyp_cpl0021 ;
    private String xyp_cpl0022;
    private String xyp_t01achzbz ;
    private String xyp_cpl0020;
    private String xyp_t01adgzza ;
    private String xyp_t01aazhbz ;
    private String xyp_t01ackzzz;
    private String xyp_t02acfzzc_aczzzc ;
    private String xyp_t01ccgzzz ;
    private String xyp_cpl0036;
    private String xyp_cpl0037 ;
    private String xyp_cpl0034;
    private String xyp_t02ccgzba_ccgzbz ;
    private String xyp_cpl0035 ;
    private String xyp_cpl0038;
    private String xyp_cpl0039 ;
    private String xyp_t01aczfzc ;
    private String xyp_cpl0032;
    private String xyp_cpl0033 ;
    private String xyp_t01aczfza ;
    private String xyp_cpl0030;
    private String xyp_cpl0031;
    private String xyp_t01acizbz;
    private String xyp_t01dezgzz ;
    private String xyp_t01delzzc;
    private String xyp_t01aaizzz;
    private String xyp_t01aafzbz ;
    private String xyp_t01aclzzz;
    private String xyp_t02ccezba_ccezbz ;
    private String xyp_t01abhzbc ;
    private String xyp_t02ccfzza_cczzza ;
    private String xyp_t01ccjzbc;
    private String xyp_t01abkzza ;
    private String xyp_t01bbzzaz ;
    private String xyp_cpl0048;
    private String xyp_cpl0045;
    private String xyp_cpl0046;
    private String xyp_t02acdzza_aczzza ;
    private String xyp_cpl0049;
    private String xyp_t01acizbc;
    private String xyp_cpl0040;
    private String xyp_t01ccbzzz ;
    private String xyp_cpl0043 ;
    private String xyp_cpl0044;
    private String xyp_cpl0041 ;
    private String xyp_t02acfzbc_acfzbz ;
    private String xyp_cpl0042;
    private String xyp_t01aclzzc;
    private String xyp_t01aalzbc;
    private String xyp_t02ackzza_ackzzz ;
    private String xyp_t01aczgzz ;
    private String xyp_t02acgzbc_acgzbz ;
    private String xyp_t01ccjzaz ;
    private String xyp_t01cczzbc;
    private String xyp_t01acizba ;
    private String xyp_t02aclzza_aclzzz ;
    private String xyp_t01aazfbc ;
    private String xyp_t01aalzbz;
    private String xyp_t01aczzbc;
    private String xyp_t01ccezzz ;
    private String xyp_t01aczzaz ;
    private String xyp_t01aajzza ;
    private String xyp_t02dezfzz_dezzzz ;
    private String xyp_t01acjzbc;
    private String xyp_t02aclzba_aclzbz ;
    private String xyp_t01aajzzc;
    private String xyp_t01dekzbc;
    private String xyp_t02aclzbc_aclzbz;
    private String xyp_t01acjzaz ;
    private String xyp_t01dezhba ;
    private String xyp_t01aagzaz ;
    private String xyp_t01acbzzz ;
    private String xyp_t01ccbzbz ;
    private String xyp_t01abzgza ;
    private String xyp_t02ccezba_cczzba ;
    private String xyp_t02ccizza_cczzza ;
    private String xyp_t01abzgzc ;
    private String xyp_t01aazzzc;
    private String xyp_t01acjzba ;
    private String xyp_t02ccizzc_cczzzc;
    private String xyp_t01dezhbc ;
    private String xyp_t01cchzaz ;
    private String xyp_t01abfzzz ;
    private String xyp_t01cczhza ;
    private String xyp_t03td061;
    private String xyp_t01cczhzc ;
    private String xyp_t01acgzza ;
    private String xyp_t02aczzza_aczzzz ;
    private String xyp_t01cchzbc ;
    private String xyp_t02acizza_aczzza ;
    private String xyp_t01cckzzc;
    private String xyp_t01adkzbc;
    private String xyp_t02cchzbc_cchzbz ;
    private String xyp_t01acdzbz ;
    private String xyp_t01abfzza ;
    private String xyp_t01abfzzc ;
    private String xyp_t01aagzbz ;
    private String xyp_t01aczfzz ;
    private String xyp_t02dezezz_dezzzz ;
    private String xyp_t01acgzzz ;
    private String xyp_t01achzzc ;
    private String xyp_t01cczhzz ;
    private String xyp_t02ccgzbc_ccgzbz ;
    private String xyp_t01dejzbz;
    private String xyp_t02ccgzza_ccgzzz ;
    private String xyp_t01acezbz ;
    private String xyp_var10 ;
    private String xyp_t01abzfzc ;
    private String xyp_t01aabzbz ;
    private String xyp_t01adfzbz ;
    private String xyp_t01cczgza ;
    private String xyp_t02acizba_acizbz ;
    private String xyp_cpl0009 ;
    private String xyp_t01cczgzc ;
    private String xyp_t01bazzza ;
    private String xyp_t0400004;
    private String xyp_t0400003;
    private String xyp_t0400002;
    private String xyp_t01bazzzc;
    private String xyp_t01acjzbz;
    private String xyp_t01ccfzzz ;
    private String xyp_cpl0001;
    private String xyp_t01adzgbc ;
    private String xyp_cpl0002;
    private String xyp_cpl0007;
    private String xyp_cpl0008;
    private String xyp_t01aazhzc ;
    private String xyp_t01adizzz;
    private String xyp_t01adizzc;
    private String xyp_t01dejzbc;
    private String xyp_t01abizbz;
    private String xyp_t02acfzba_acfzbz ;
    private String xyp_t02cczzzc_cczzzz;
    private String xyp_t02ccfzba_cczzba ;
    private String xyp_t02acgzba_acgzbz ;
    private String xyp_t01aczezz ;
    private String xyp_t01acezba;
}
